export const SELECT_USER = "SELECT_USER";
export const RESET_SELECTED_USER = "RESET_SELECTED_USER";

export const SELECT_VANBANDEN_DOKHAN = 'SELECT_VANBANDEN_DOKHAN';
export const SET_VANBANDEN_DOKHAN = 'SET_VANBANDEN_DOKHAN';


export const SELECT_VANBANDEN_DOMAT = 'SELECT_VANBANDEN_DOMAT';
export const SET_VANBANDEN_DOMAT = 'SET_VANBANDEN_DOMAT';

export const SELECT_VANBANDEN_LINHVUC = 'SELECT_VANBANDEN_LINHVUC';
export const SET_VANBANDEN_LINHVUC = 'SET_VANBANDEN_LINHVUC';

export const SELECT_VANBANDEN_LOAI = 'SELECT_VANBANDEN_LOAI';
export const SET_VANBANDEN_LOAI = 'SET_VANBANDEN_LOAI';

export const SELECT_VANBANDI_DOUUTIEN = 'SELECT_VANBANDI_DOUUTIEN';
export const SET_VANBANDI_DOUUTIEN = 'SET_VANBANDI_DOUUTIEN';

export const SELECT_VANBANDI_DOQUANTRONG = 'SELECT_VANBANDI_DOQUANTRONG';
export const SET_VANBANDI_DOQUANTRONG = 'SET_VANBANDI_DOQUANTRONG';

export const SELECT_VANBANDI_LINHVUC = 'SELECT_VANBANDI_LINHVUC';
export const SET_VANBANDI_LINHVUC = 'SET_VANBANDI_LINHVUC';

export const SELECT_VANBANDI_LOAI = 'SELECT_VANBANDI_LOAI';
export const SET_VANBANDI_LOAI = 'SET_VANBANDI_LOAI';



