const images = {
  background: require('../assets/images/background.png'),
  ribbonBackground: require('../assets/images/ribbon-background.png'),
  showPasswordIcon: require('../assets/images/visible-eye.png'),
  hidePasswordIcon: require('../assets/images/hidden-eye.png'),
  userAvatar: require('../assets/images/avatar.png'),
  subItemIconLink: require('../assets/images/arrow-white-right.png'),
  logo: require('../assets/images/new_logo.png'),
  vanbandenIcons: {
    chua_xuly: require('../assets/images/Dashboard_icon/van_ban_den/chua_xu_ly.png'),
    da_xuly: require('../assets/images/Dashboard_icon/van_ban_den/da_xu_ly.png'),
    noibo_chua_xuly: require('../assets/images/Dashboard_icon/van_ban_den/noi_bo_chua_xu_ly.png'),
    noibo_da_xuly: require('../assets/images/Dashboard_icon/van_ban_den/noi_bo_da_xu_ly.png'),
    thamgia_xuly: require('../assets/images/Dashboard_icon/van_ban_den/tham_gia_xu_ly.png'),
  },
  vanbandiIcons: {
    chua_xuly: require('../assets/images/Dashboard_icon/van_ban_di/chua_xu_ly.png'),
    da_xuly: require('../assets/images/Dashboard_icon/van_ban_di/da_xu_ly.png'),
    thamgia_xuly: require('../assets/images/Dashboard_icon/van_ban_di/tham_gia_xu_ly.png'),
    ban_hanh: require('../assets/images/Dashboard_icon/van_ban_di/da_ban_hanh.png'),
  },
  congviecIcons: {
    ca_nhan: require('../assets/images/Dashboard_icon/cong_viec/ca_nhan.png'),
    duoc_giao: require('../assets/images/Dashboard_icon/cong_viec/duoc_giao.png'),
    cho_xac_nhan: require('../assets/images/Dashboard_icon/cong_viec/cho_xac_nhan.png'),
    phoi_hop_xu_ly: require('../assets/images/Dashboard_icon/cong_viec/phoi_hop_xu_ly.png'),
    them_moi: require('../assets/images/Dashboard_icon/cong_viec/them_moi.png'),
    cua_thu_ky: require('../assets/images/Dashboard_icon/cong_viec/cua_thu_ky.png'),
  },
  otherIcons: {
    lich_cong_tac: require('../assets/images/Dashboard_icon/tien_ich/lich_cong_tac.png'),
    dat_xe: require('../assets/images/Dashboard_icon/tien_ich/dat_xe.png'),
    chuyen_xe: require('../assets/images/Dashboard_icon/tien_ich/chuyen_xe.png'),
    phong_hop: require('../assets/images/Dashboard_icon/tien_ich/phong_hop.png'),
    lich_truc: require('../assets/images/Dashboard_icon/tien_ich/lich_truc.png'),
    uy_quyen: require('../assets/images/Dashboard_icon/tien_ich/uy_quyen.png'),
    nhac_nho: require('../assets/images/Dashboard_icon/tien_ich/nhac_nho.png'),
    khac: require('../assets/images/Dashboard_icon/tien_ich/khac.png'),
    lich_truc_ca_nhan: require('../assets/images/Dashboard_icon/tien_ich/lich_truc_ca_nhan.png'),
  },
  hotPickIcons: {
    van_ban_den: require('../assets/images/Dashboard_icon/hot_pick/van_ban_den_chua_xu_ly.png'),
    van_ban_di: require('../assets/images/Dashboard_icon/hot_pick/van_ban_di_chua_xu_ly.png'),
    cong_viec_ca_nhan: require('../assets/images/Dashboard_icon/hot_pick/cong_viec_ca_nhan.png'),
    tien_ich: require('../assets/images/Dashboard_icon/hot_pick/tien_ich.png'),
  },
  icon_phe_duyet: require('../assets/images/icon_phe_duyet.png'),
}

export default images;